// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpc/v1/iam.proto

package kiwi_iam_user_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe5f1fdc4a91f6e, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserResponse struct {
	EmployeeNumber       int64    `protobuf:"varint,1,opt,name=employee_number,json=employeeNumber,proto3" json:"employee_number,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Position             string   `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Department           string   `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`
	Location             string   `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	IsVendor             bool     `protobuf:"varint,8,opt,name=is_vendor,json=isVendor,proto3" json:"is_vendor,omitempty"`
	Manager              string   `protobuf:"bytes,9,opt,name=manager,proto3" json:"manager,omitempty"`
	TeamMembership       []string `protobuf:"bytes,10,rep,name=team_membership,json=teamMembership,proto3" json:"team_membership,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe5f1fdc4a91f6e, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetEmployeeNumber() int64 {
	if m != nil {
		return m.EmployeeNumber
	}
	return 0
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *UserResponse) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

func (m *UserResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UserResponse) GetIsVendor() bool {
	if m != nil {
		return m.IsVendor
	}
	return false
}

func (m *UserResponse) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *UserResponse) GetTeamMembership() []string {
	if m != nil {
		return m.TeamMembership
	}
	return nil
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "kiwi.iam.user.v1.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "kiwi.iam.user.v1.UserResponse")
}

func init() { proto.RegisterFile("api/grpc/v1/iam.proto", fileDescriptor_dfe5f1fdc4a91f6e) }

var fileDescriptor_dfe5f1fdc4a91f6e = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0x23, 0x41,
	0x10, 0x86, 0xc9, 0xf7, 0x4c, 0xed, 0x92, 0x5d, 0x9a, 0x5d, 0x68, 0x22, 0x09, 0x21, 0x1e, 0xcc,
	0x69, 0x42, 0xf4, 0x17, 0x78, 0xf0, 0x20, 0x92, 0x20, 0x03, 0x7a, 0x1d, 0x3a, 0x49, 0x19, 0x0b,
	0xa7, 0x3f, 0xec, 0xee, 0x24, 0xf8, 0xf3, 0xfc, 0x67, 0xd2, 0x3d, 0x19, 0x0d, 0x82, 0xc7, 0xf7,
	0x79, 0xa6, 0x6a, 0xe8, 0x7a, 0xe1, 0xbf, 0x30, 0x34, 0xdb, 0x5a, 0xb3, 0x9e, 0xed, 0xe7, 0x33,
	0x12, 0x32, 0x33, 0x56, 0x7b, 0xcd, 0xfe, 0xbe, 0xd0, 0x81, 0xb2, 0x90, 0x77, 0x0e, 0x6d, 0xb6,
	0x9f, 0x4f, 0xce, 0xe1, 0xd7, 0x83, 0x43, 0x9b, 0xe3, 0xeb, 0x0e, 0x9d, 0x67, 0xff, 0xa0, 0x83,
	0x52, 0x50, 0xc9, 0x1b, 0xe3, 0xc6, 0x34, 0xcd, 0xab, 0x30, 0x79, 0x6f, 0xc2, 0xef, 0xea, 0x2b,
	0x67, 0xb4, 0x72, 0xc8, 0x2e, 0xe0, 0x0f, 0x4a, 0x53, 0xea, 0x37, 0xc4, 0x42, 0xed, 0xe4, 0x0a,
	0x6d, 0x1c, 0x68, 0xe5, 0xfd, 0x1a, 0x2f, 0x23, 0xfd, 0xda, 0xd7, 0x3c, 0xd9, 0xc7, 0x86, 0x00,
	0x4f, 0x64, 0x9d, 0x2f, 0x94, 0x90, 0xc8, 0x5b, 0x51, 0xa5, 0x91, 0x2c, 0x85, 0x44, 0x76, 0x06,
	0x69, 0x29, 0x6a, 0xdb, 0x8e, 0x36, 0x09, 0x20, 0xca, 0x01, 0x24, 0x46, 0x3b, 0xf2, 0xa4, 0x15,
	0xef, 0x54, 0xae, 0xce, 0x6c, 0x04, 0xb0, 0x41, 0x23, 0xac, 0x97, 0xa8, 0x3c, 0xef, 0x46, 0x7b,
	0x42, 0xc2, 0x6c, 0xa9, 0xd7, 0x22, 0xce, 0xf6, 0x8e, 0x7b, 0x8f, 0x39, 0xfc, 0x94, 0x5c, 0xb1,
	0x47, 0xb5, 0xd1, 0x96, 0x27, 0xe3, 0xc6, 0x34, 0xc9, 0x13, 0x72, 0x8f, 0x31, 0x33, 0x0e, 0x3d,
	0x29, 0x94, 0xd8, 0xa2, 0xe5, 0x69, 0x9c, 0xab, 0x63, 0xb8, 0x84, 0x47, 0x21, 0x0b, 0x89, 0xe1,
	0xbd, 0xee, 0x99, 0x0c, 0x87, 0x71, 0x6b, 0x9a, 0xe6, 0xfd, 0x80, 0x17, 0x9f, 0xf4, 0xf2, 0x1e,
	0x7a, 0x77, 0x74, 0xa0, 0xdb, 0xeb, 0x05, 0xbb, 0x81, 0x76, 0xb8, 0x26, 0x1b, 0x66, 0xdf, 0xeb,
	0xc8, 0x4e, 0xba, 0x18, 0x8c, 0x7e, 0xd2, 0x55, 0x09, 0xab, 0x6e, 0xec, 0xf4, 0xea, 0x23, 0x00,
	0x00, 0xff, 0xff, 0x4e, 0x6e, 0x50, 0xec, 0xec, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KiwiIAMClient is the client API for KiwiIAM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KiwiIAMClient interface {
	User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type kiwiIAMClient struct {
	cc *grpc.ClientConn
}

func NewKiwiIAMClient(cc *grpc.ClientConn) KiwiIAMClient {
	return &kiwiIAMClient{cc}
}

func (c *kiwiIAMClient) User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/kiwi.iam.user.v1.KiwiIAM/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KiwiIAMServer is the server API for KiwiIAM service.
type KiwiIAMServer interface {
	User(context.Context, *UserRequest) (*UserResponse, error)
}

// UnimplementedKiwiIAMServer can be embedded to have forward compatible implementations.
type UnimplementedKiwiIAMServer struct {
}

func (*UnimplementedKiwiIAMServer) User(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}

func RegisterKiwiIAMServer(s *grpc.Server, srv KiwiIAMServer) {
	s.RegisterService(&_KiwiIAM_serviceDesc, srv)
}

func _KiwiIAM_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiwiIAMServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiwi.iam.user.v1.KiwiIAM/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiwiIAMServer).User(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KiwiIAM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kiwi.iam.user.v1.KiwiIAM",
	HandlerType: (*KiwiIAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "User",
			Handler:    _KiwiIAM_User_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/v1/iam.proto",
}
